[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
MicroscopePSFs = "de9ac726-48a4-48ab-84b0-1c03c7c18929"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"
